spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:healthdb
    username: sa
    password:
    driverClassName: org.h2.Driver
params:
  mapsKey: ${KEY_MAPS}